### ISSUE TITLE
Captcha gets no new image on refresh click by use default Captcha template

### ISSUE THREAD

**Issue by pengmaradi** [maikschneider/bw_captcha#38] opened 2023-08-25 13:44 UTC
Hello @markussoeth

I got page 404 such as domain.tld?type=3413&1692970543369=
the reason is TYPO3 FE cacheHash excludedParameters has no "1692970543369"
I have to override the Captcha.html to set ```let captchaUrl = this.dataset.url; this.previousElementSibling.setAttribute('src', captchaUrl + (/\?/.test(captchaUrl) ? '&now=' : '?now=') + Date.now());```
and add "now" as excludedParameters parameter.

or remove ```+ (/\?/.test(captchaUrl) ? '&now=' : '?now=') + Date.now()``` it works

https://github.com/maikschneider/bw_captcha/blob/development/Resources/Private/Frontend/Partials/Captcha.html#L9C8-L9C13

Regards
Xiaoling Peng

**Comment by maikschneider** [comment] 2023-08-25 13:57
Hey Xiaoling, thanks for the bug report! That's a very good point. Very strange that no-one ran into this problem before.

I'd prefer to introduce a named parameter, like you suggested. I'll do some tests very soon.

**Comment by mgerdes-atl** [comment] 2023-08-30 18:54
Hi @maikschneider ,
just jumping on this issue. If you introduce a named parameter would you please add the timestamp to the first image creation which is not done via JS.

Otherwise we might have a caching issue here. In our case the cache header is added via the webserver, because the mimetype is image. This results in loading the captcha from browsers cache.

Workaround would be to turn off webservers automatically cache header feature. But I think it would be better to reduce setup difficulties with the cache this way.

Regards Markus

**Comment by sergej-plusB** [comment] 2023-08-31 12:05
I had in general the problem that the Captcha Image was cached. On the 3.0.1 version I changed this line in the Captcha.html. I just added a timestamp to the page type.

`<img src="{f:uri.page(pageType:3413)}&timestamp={f:format.date(date: 'now', format: 'U')}" alt="Captcha image" loading="lazy" onload="this.parentElement.classList.remove('captcha--reloading'); return false;"/>`

**Comment by boosim** [comment] 2023-09-01 08:43
I had that problem with the browser cache as well. It seems a bit curious to me why this problem isn't discussed more as it will probably occur for everyone? It would be really cool to add some solution for this to the extension or documentation.

I have come up with a solution similar to that of sergej-plusB but using Javascript instead. 
This code basically forces the browser to load a new captcha image after the page is loaded by also adding a timestamp at the end of the URL.

$( document ).ready(function() {
        var url = $(".captcha img").attr("src");
        $(".captcha img").attr("src", url + `&v=${new Date().getTime()}`);
});

**Comment by maikschneider** [comment] 2023-09-01 09:26
Thanks for the response! I will look into it very soon. I hope to resolve this issue by setting special cache headers in the middleware response. Using JS seems a bit hacky.

**Comment by boosim** [comment] 2023-09-01 09:41
Thank you very much.

You are of course right, the JS solution isn't perfect for this. I just wanted to have a solution I could deploy without changing anything in the extension to avoid problems on later updates.

**Comment by maikschneider** [comment] 2023-09-03 21:45
Hey guys, 
I just created a PR #42 which should solve both issues. I tested it with an apache webserver and default `.htaccess` configuration. Could you please test with your setup?

**Comment by boosim** [comment] 2023-09-04 09:38
Hi @maikschneider,

I just did a test on a new project of ours with your fix and it seems to work fine. I couldn't find any previous browser caching problems. Thanks a lot for this.

One small issue happened to me. When I click the reload icon next to the captcha to get a new image, the icon starts spinning but doesn't stop. But a new captcha image is still loaded and it works when I send the form with the right code.
When I click the icon again a second or third time while the icon is still spinning, again a new captcha image is loaded and it works as well with the right code.

It seems to work as expected, only the image should stop spinning after the image ist loaded as this could be confusing for users.

Many thanks again for your work.

**Comment by maikschneider** [comment] 2023-09-04 09:52
Hi @boosim, I'm glad to hear that the fix works for you. There was [an issue](https://github.com/maikschneider/bw_captcha/issues/32) in v3.0.0 with the reloading (animation) which was fixed in [v3.0.1](https://github.com/maikschneider/bw_captcha/releases/tag/v3.0.1). Could you please test with the current version?

@pengmaradi Could you check if the the cHash issue solved for you?

**Comment by maikschneider** [comment] 2023-09-04 15:21
Hey @boosim,

I do not get a HTTP error, however the image reloading is very slow when logged in the backend. When removing some headers, I noticed that the `Content-Length` header is the cause.. I updated the PR and add the header only for onload requests. Could you please test again?

Thank you very much!

**Comment by pengmaradi** [comment] 2023-09-05 11:30
Hi @maikschneider yes, the cHash issue solved is for me. thank you :)

**Closed** 2023-09-05 11:55 UTC
